api:
  autodiscoveryId: "123456"  

http:
  host: "0.0.0.0"
  port: "8083"
  
https:
  host: "0.0.0.0"
  port: "8084"
  
tls:
  type: "JKS"
  path: "Prowess-SSL-Keystore.jks"
  alias: "*.esb.internal.prowess.com"
  keypassword: test123
  password: test123
